import { AssetsDataType } from "./types";

export const assetsData: AssetsDataType = {
  stocks: [
    {
      name: "Aditya Birla Capital",
      full_name: "Aditya Birla Capital Ltd",
      isin: "INE674K01013",
      id: 7310,
      currency: "INR",
      symbol: "ADTB",
      TVsymbol: "BSE:ABCAPITAL",
      image: "/images/stocks/ADTB.png",
    },
    {
      name: "ACC",
      full_name: "ACC Ltd",
      isin: "INE012A01025",
      id: 17980,
      currency: "INR",
      symbol: "ACC",
      TVsymbol: "BSE:ACC",
      image: "/images/stocks/ACC.png",
    },
    {
      name: "Adani Enterprises",
      full_name: "Adani Enterprises Ltd",
      isin: "INE423A01024",
      id: 17984,
      currency: "INR",
      symbol: "ADEL",
      TVsymbol: "BSE:ADANIENT",
      image: "/images/stocks/ADANI.svg",
    },
    {
      name: "Adani Power",
      full_name: "Adani Power Ltd",
      isin: "INE814H01011",
      id: 39351,
      currency: "INR",
      symbol: "ADAN",
      TVsymbol: "BSE:ADANIPOWER",
      image: "/images/stocks/ADANI.svg",
    },
    {
      name: "Ambuja Cements",
      full_name: "Ambuja Cements Ltd.",
      isin: "INE079A01024",
      id: 17998,
      currency: "INR",
      symbol: "ABUJ",
      TVsymbol: "BSE:AMBUJACEM",
      image: "/images/stocks/ambuja.webp",
    },
    {
      name: "Apollo Hospitals",
      full_name: "Apollo Hospitals Enterprises Ltd.",
      isin: "INE437A01024",
      id: 18004,
      currency: "INR",
      symbol: "APLH",
      TVsymbol: "BSE:APOLLOHOSP",
      image: "/images/stocks/Apollo_Hospitals.svg",
    },
    {
      name: "Bharti Airtel",
      full_name: "Bharti Airtel Ltd.",
      isin: "INE397D01024",
      id: 18041,
      currency: "INR",
      symbol: "BRTI",
      TVsymbol: "BSE:AIRTELPP",
      image: "/images/stocks/bharti-airtel.jpg",
    },
    {
      name: "Tata Steel BSL",
      full_name: "Tata Steel BSL Ltd",
      isin: "INE824B01021",
      id: 18044,
      currency: "INR",
      symbol: "TATS",
      TVsymbol: "BSE:TATASTLBSL",
      image: "/images/stocks/Tata-Steel-BSL.jpg",
    },
    {
      name: "Bank Of Baroda",
      full_name: "Bank of Baroda Ltd",
      isin: "INE028A01039",
      id: 18047,
      currency: "INR",
      symbol: "BOB",
      TVsymbol: "BSE:BANKBARODA",
      image: "/images/stocks/Bank-of-Baroda.jpg",
    },
    {
      name: "CBI",
      full_name: "Central Bank of India Ltd",
      isin: "INE483A01010",
      id: 18062,
      currency: "INR",
      symbol: "CBI",
      TVsymbol: "BSE:CENTRALBK",
      image: "/images/stocks/cbi.webp",
    },
    {
      name: "HDFC Bank",
      full_name: "HDFC Bank Ltd",
      isin: "INE040A01034",
      id: 18177,
      currency: "INR",
      symbol: "HDBK",
      TVsymbol: "BSE:HDFCBANK",
      image: "/images/stocks/hdfc.png",
    },
    {
      name: "Hero MotoCorp",
      full_name: "Hero MotoCorp Ltd",
      isin: "INE158A01026",
      id: 18179,
      currency: "INR",
      symbol: "HROM",
      TVsymbol: "BSE:HEROMOTOCO",
      image: "/images/stocks/Hero_MotoCorp.svg",
    },
    {
      name: "Indian Oil",
      full_name: "Indian Oil Corporation Ltd",
      isin: "INE242A01010",
      id: 18197,
      currency: "INR",
      symbol: "IOC",
      TVsymbol: "BSE:IOC",
      image: "/images/stocks/Indian_Oil.svg",
    },
    {
      name: "ICICI Bank",
      full_name: "ICICI Bank Ltd",
      isin: "INE090A01021",
      id: 18198,
      currency: "INR",
      symbol: "ICBK",
      TVsymbol: "BSE:ICICIBANK",
      image: "/images/stocks/icici-bank.webp",
    },
    {
      name: "Jindal Steel&Power",
      full_name: "Jindal Steel & Power Ltd",
      isin: "INE749A01030",
      id: 18241,
      currency: "INR",
      symbol: "JNSP",
      TVsymbol: "BSE:JINDALSTEL",
      image: "/images/stocks/jindal.png",
    },
    {
      name: "Kotak Mahindra Bank",
      full_name: "Kotak Mahindra Bank Ltd.",
      isin: "INE237A01028",
      id: 18260,
      currency: "INR",
      symbol: "KTKM",
      TVsymbol: "BSE:KOTAKBANK",
      image: "/images/stocks/kotak.jpg",
    },
    {
      name: "M.R.F.",
      full_name: "M.R.F. Ltd.",
      isin: "INE883A01011",
      id: 18291,
      currency: "INR",
      symbol: "MRF",
      TVsymbol: "BSE:MRF",
      image: "/images/stocks/Mrf.png",
    },
    {
      name: "Reliance Communications",
      full_name: "Reliance Communications Ltd",
      isin: "INE330H01018",
      id: 18362,
      currency: "INR",
      symbol: "RLCM",
      TVsymbol: "BSE:RCOM",
      image: "/images/stocks/reliance-communication.svg",
    },
    {
      name: "Reliance Industries",
      full_name: "Reliance Industries Ltd",
      isin: "INE002A01018",
      id: 18367,
      currency: "INR",
      symbol: "RELI",
      TVsymbol: "BSE:RELIANCE",
      image: "/images/stocks/reliance-industries.jpg",
    },
    {
      name: "SBI",
      full_name: "State Bank Of India",
      isin: "INE062A01020",
      id: 18376,
      currency: "INR",
      symbol: "SBI",
      TVsymbol: "BSE:SBIN",
      image: "/images/stocks/State_Bank_of_India.svg",
    },
    {
      name: "Taj GVK",
      full_name: "TAJ GVK Hotels and Resorts Ltd",
      isin: "INE586B01026",
      id: 18416,
      currency: "INR",
      symbol: "TAJG",
      TVsymbol: "BSE:TAJGVK",
      image: "/images/stocks/TAJGVK-Hotels-and-Resorts-Limited.jpg",
    },
    {
      name: "Tata Consultancy",
      full_name: "Tata Consultancy Services Ltd.",
      isin: "INE467B01029",
      id: 18420,
      currency: "INR",
      symbol: "TCS",
      TVsymbol: "BSE:TCS",
      image: "/images/stocks/tcs.png",
    },
    {
      name: "Tata Motors",
      full_name: "Tata Motors Ltd",
      isin: "INE155A01022",
      id: 18425,
      currency: "INR",
      symbol: "TAMO",
      TVsymbol: "BSE:TATAMOTORS",
      image: "/images/stocks/tata-motors.jpg",
    },
    {
      name: "Tata Steel Ltd",
      full_name: "Tata Steel Ltd",
      isin: "INE081A01012",
      id: 18428,
      currency: "INR",
      symbol: "TISC",
      TVsymbol: "BSE:TATASTEEL",
      image: "/images/stocks/tata-steel.png",
    },
    {
      name: "Tech Mahindra",
      full_name: "Tech Mahindra Ltd",
      isin: "INE669C01036",
      id: 18429,
      currency: "INR",
      symbol: "TEML",
      TVsymbol: "BSE:TECHM",
      image: "/images/stocks/tech-mahindra.webp",
    },
    {
      name: "TVS Motor Company",
      full_name: "TVS Motor Company Ltd.",
      isin: "INE494B01023",
      id: 18442,
      currency: "INR",
      symbol: "TVSM",
      TVsymbol: "BSE:TVSMOTOR",
      image: "/images/stocks/TVS_Motor_Company.jpg",
    },
    {
      name: "Wipro",
      full_name: "Wipro Ltd",
      isin: "INE075A01022",
      id: 18467,
      currency: "INR",
      symbol: "WIPR",
      TVsymbol: "BSE:WIPRO",
      image: "/images/stocks/Wipro.svg",
    },
  ],

  indices: [
    {
      name: "Nifty 50",
      id: 17940,
      symbol: "NSEI",
      currency: "INR",
      TVsymbol: undefined,
      image: "/images/indices/Nifty_50.svg",
    },
    {
      name: "Nifty 100",
      id: 17943,
      symbol: "NIFTY100",
      currency: "INR",
      TVsymbol: undefined,
      image: "/images/indices/Nifty_100.jpg",
    },
    {
      name: "BSE Consumer Durables",
      id: 39940,
      symbol: "BSECD",
      currency: "INR",
      TVsymbol: "BSE:CD",
      image: null,
    },
    {
      name: "BSE Sensex",
      id: 39929,
      symbol: "BSESN",
      currency: "INR",
      TVsymbol: "BSE:SENSEX",
      image: "/images/indices/BSE_Sensex.svg",
    },
    {
      name: "BSE SmallCap",
      id: 39937,
      symbol: "SPBSESC",
      currency: "INR",
      TVsymbol: "BSE:SMLCAP",
      image: null,
    },
    {
      name: "BSE Bharat 22",
      id: 1066768,
      symbol: "SPBSEBH",
      currency: "INR",
      TVsymbol: "BSE:BHRT22",
      image: null,
    },
    {
      name: "BSE Sensex Next 50",
      id: 1066777,
      symbol: "SPBSESNXT50",
      currency: "INR",
      TVsymbol: "BSE:SNXT50",
      image: "/images/indices/BSE_Sensex.svg",
    },
    {
      name: "BSE Sensex 50",
      id: 1066776,
      symbol: "SPBSESN50",
      currency: "INR",
      TVsymbol: "BSE:SNSX50",
      image: "/images/indices/BSE_Sensex.svg",
    },
    {
      name: "BSE India Manufacturing",
      id: 1066771,
      symbol: "SPBIMIP",
      currency: "INR",
      TVsymbol: "BSE:MFG",
      image: null,
    },
    {
      name: "Nifty Alpha 50",
      id: 946615,
      symbol: "NIFTYALI",
      currency: "INR",
      TVsymbol: undefined,
      image: null,
    },
  ],
  currency_crosses: [
    {
      name: "AUD/USD",
      symbol: "AUDUSD",
      id: 5,
      base: "AUD",
      base_name: "Australian Dollar",
      base_image: "/images/currency-cross/AUD.svg",
      second: "USD",
      second_name: "US Dollar",
      second_image: "/images/currency-cross/USD.svg",
      TVsymbol: "FX:AUDUSD",
    },
    {
      name: "USD/AUD",
      symbol: "USDAUD",
      id: 2091,
      base: "USD",
      base_name: "US Dollar",
      base_image: "/images/currency-cross/USD.svg",
      second: "AUD",
      second_name: "Australian Dollar",
      second_image: "/images/currency-cross/AUD.svg",
      TVsymbol: "SAXO:USDAUD",
    },
    {
      name: "EUR/AUD",
      symbol: "EURAUD",
      id: 15,
      base: "EUR",
      base_name: "Euro",
      base_image: "/images/currency-cross/EUR.png",
      second: "AUD",
      second_name: "Australian Dollar",
      second_image: "/images/currency-cross/AUD.svg",
      TVsymbol: "FX:EURAUD",
    },
    {
      name: "AUD/EUR",
      symbol: "AUDEUR",
      id: 1487,
      base: "AUD",
      base_name: "Australian Dollar",
      base_image: "/images/currency-cross/AUD.svg",
      second: "EUR",
      second_name: "Euro",
      second_image: "/images/currency-cross/EUR.png",
      TVsymbol: "SAXO:AUDEUR",
    },
    {
      name: "AUD/CAD",
      symbol: "AUDCAD",
      id: 47,
      base: "AUD",
      base_name: "Australian Dollar",
      base_image: "/images/currency-cross/AUD.svg",
      second: "CAD",
      second_name: "Canadian Dollar",
      second_image: "/images/currency-cross/CAD.svg",
      TVsymbol: "FX:AUDCAD",
    },
    {
      name: "CAD/AUD",
      symbol: "CADAUD",
      id: 1522,
      base: "CAD",
      base_name: "Canadian Dollar",
      base_image: "/images/currency-cross/CAD.svg",
      second: "AUD",
      second_name: "Australian Dollar",
      second_image: "/images/currency-cross/AUD.svg",
      TVsymbol: "FX_IDC:CADAUD",
    },
    {
      name: "AUD/CHF",
      symbol: "AUDCHF",
      id: 48,
      base: "AUD",
      base_name: "Australian Dollar",
      base_image: "/images/currency-cross/AUD.svg",
      second: "CHF",
      second_name: "Swiss Franc",
      second_image: "/images/currency-cross/CHF.svg",
      TVsymbol: "FX:AUDCHF",
    },
    {
      name: "CHF/AUD",
      symbol: "CHFAUD",
      id: 1542,
      base: "CHF",
      base_name: "Swiss Franc",
      base_image: "/images/currency-cross/CHF.svg",
      second: "AUD",
      second_name: "Australian Dollar",
      second_image: "/images/currency-cross/AUD.svg",
      TVsymbol: "SAXO:CHFAUD",
    },
    {
      name: "AUD/JPY",
      symbol: "AUDJPY",
      id: 49,
      base: "AUD",
      base_name: "Australian Dollar",
      base_image: "/images/currency-cross/AUD.svg",
      second: "JPY",
      second_name: "Japanese Yen",
      second_image: "/images/currency-cross/JPY.png",
      TVsymbol: "FX:AUDJPY",
    },
    {
      name: "JPY/AUD",
      symbol: "JPYAUD",
      id: 1889,
      base: "JPY",
      base_name: "Japanese Yen",
      base_image: "/images/currency-cross/JPY.png",
      second: "AUD",
      second_name: "Australian Dollar",
      second_image: "/images/currency-cross/AUD.svg",
      TVsymbol: "FX_IDC:JPYAUD",
    },
    {
      name: "USD/JPY",
      symbol: "USDJPY",
      id: 3,
      base: "USD",
      base_name: "US Dollar",
      base_image: "/images/currency-cross/USD.svg",
      second: "JPY",
      second_name: "Japanese Yen",
      second_image: "/images/currency-cross/JPY.png",
      TVsymbol: "FX:USDJPY",
    },
    {
      name: "JPY/USD",
      symbol: "JPYUSD",
      id: 1910,
      base: "JPY",
      base_name: "Japanese Yen",
      base_image: "/images/currency-cross/JPY.png",
      second: "USD",
      second_name: "US Dollar",
      second_image: "/images/currency-cross/USD.svg",
      TVsymbol: "SAXO:JPYUSD",
    },
    {
      name: "USD/CAD",
      symbol: "USDCAD",
      id: 7,
      base: "USD",
      base_name: "US Dollar",
      base_image: "/images/currency-cross/USD.svg",
      second: "CAD",
      second_name: "Canadian Dollar",
      second_image: "/images/currency-cross/CAD.svg",
      TVsymbol: "FX:USDCAD",
    },
    {
      name: "CAD/USD",
      symbol: "CADUSD",
      id: 1538,
      base: "CAD",
      base_name: "Canadian Dollar",
      base_image: "/images/currency-cross/CAD.svg",
      second: "USD",
      second_name: "US Dollar",
      second_image: "/images/currency-cross/USD.svg",
      TVsymbol: "SAXO:CADUSD",
    },
    {
      name: "EUR/USD",
      symbol: "EURUSD",
      id: 1,
      base: "EUR",
      base_name: "Euro",
      base_image: "/images/currency-cross/EUR.png",
      second: "USD",
      second_name: "US Dollar",
      second_image: "/images/currency-cross/USD.svg",
      TVsymbol: "FX:EURUSD",
    },
    {
      name: "USD/EUR",
      symbol: "USDEUR",
      id: 2124,
      base: "USD",
      base_name: "US Dollar",
      base_image: "/images/currency-cross/USD.svg",
      second: "EUR",
      second_name: "Euro",
      second_image: "/images/currency-cross/EUR.png",
      TVsymbol: "BITTREX:USDEUR",
    },
    {
      name: "USD/INR",
      symbol: "USDINR",
      id: 160,
      base: "USD",
      base_name: "US Dollar",
      base_image: "/images/currency-cross/USD.svg",
      second: "INR",
      second_name: "Indian Rupee",
      second_image: "/images/currency-cross/INR.svg",
      TVsymbol: "VANTAGE:USDINR",
    },
    {
      name: "INR/USD",
      symbol: "USDINR",
      id: 941148,
      base: "INR",
      base_name: "Indian Rupee",
      base_image: "/images/currency-cross/INR.svg",
      second: "USD",
      second_name: "US Dollar",
      second_image: "/images/currency-cross/USD.svg",
      TVsymbol: "FX_IDC:INRUSD",
    },
    {
      name: "EUR/JPY",
      symbol: "EURJPY",
      id: 9,
      base: "EUR",
      base_name: "Euro",
      base_image: "/images/currency-cross/EUR.png",
      second: "JPY",
      second_name: "Japanese Yen",
      second_image: "/images/currency-cross/JPY.png",
      TVsymbol: "FX:EURJPY",
    },
    {
      name: "JPY/EUR",
      symbol: "JPYEUR",
      id: 1895,
      base: "JPY",
      base_name: "Japanese Yen",
      base_image: "/images/currency-cross/JPY.png",
      second: "EUR",
      second_name: "Euro",
      second_image: "/images/currency-cross/EUR.png",
      TVsymbol: "SAXO:JPYEUR",
    },
  ],
  crypto_currencies: [
    {
      name: "Bitcoin",
      symbol: "BTC",
      TVsymbol: "BITSTAMP:BTCUSD",
      id: 1057391,
      currency: "USD",
      image: "/images/crypto/Bitcoin.svg"
    },
    {
      name: "Ethereum",
      symbol: "ETH",
      TVsymbol: "BITSTAMP:ETHUSD",
      id: 1061443,
      currency: "USD",
      image: "/images/crypto/Ethereum.svg"
    },
    {
      name: "Binance Coin",
      symbol: "BNB",
      TVsymbol: "BINANCE:BNBUSD",
      id: 1061448,
      currency: "USD",
      image: "/images/crypto/Binance-coin.png"
    },
    {
      name: "Tether",
      symbol: "USDT",
      TVsymbol: "BITSTAMP:USDTUSD",
      id: 1061453,
      currency: "USD",
      image: "/images/crypto/tether.png"
    },
    {
      name: "Cardano",
      symbol: "ADA",
      TVsymbol: "BITSTAMP:ADAUSD",
      id: 1062537,
      currency: "USD",
      image: "/images/crypto/Cardano.png"
    },
    {
      name: "Dogecoin",
      symbol: "DOGE",
      TVsymbol: "BITSTAMP:DOGEUSD",
      id: 1061477,
      currency: "USD",
      image: "/images/crypto/Dogecoin.png"
    },
    {
      name: "Solana",
      symbol: "SOL",
      TVsymbol: "BITSTAMP:SOLUSD",
      id: 1161528,
      currency: "USD",
      image: "/images/crypto/Solana.png"
    },
    {
      name: "SushiSwap",
      symbol: "SUSHI",
      TVsymbol: "BITSTAMP:SUSHIUSD",
      id: 1168117,
      currency: "USD",
      image: "/images/crypto/sushiswap.svg"
    },
    {
      name: "Dash",
      symbol: "DASH",
      TVsymbol: "BITFINEX:DSHUSD",
      id: 1061456,
      currency: "USD",
      image: "/images/crypto/dash.png"
    },
    {
      name: "Theta Fuel",
      symbol: "TFUEL",
      TVsymbol: "BINANCE:TFUELUSD",
      id: 1138421,
      currency: "USD",
      image: "/images/crypto/theta-fuel.svg"
    },
    {
      name: "The Graph",
      symbol: "GRT",
      TVsymbol: "BITSTAMP:GRTUSD",
      id: 1168375,
      currency: "USD",
      image: "/images/crypto/the-graph.svg"
    },
    {
      name: "Polygon",
      symbol: "MATIC",
      TVsymbol: "BITSTAMP:MATICUSD",
      id: 1138411,
      currency: "USD",
      image: "/images/crypto/polygon.svg"
    }
  ]
};
